site_name: Project OMEGA
theme: readthedocs
nav:
  - Home:
    - "About": "index.md"
  - "Tutorials":
    - "Getting started": "getting-started.md"
markdown_extensions:
  - admonition
extra_css: [res/extra.css]
